version: "3"
 
services:
 mini-php:
    build:
      context: "../.."
      dockerfile: "docker/stag/php/Dockerfile"
    image: ${APP_IMAGE}
    #image: "mamat08nurahmat/php-cicd:latest"
    #ports:
    #  - "${APP_PORT}:80"
    #mem_limit: 128MB
    #mem_reservation: 64MB
    restart: always

